# Generated by Django 2.2.6 on 2019-11-21 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0002_auto_20191121_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='faexpects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
    ]
