# Generated by Django 2.2.7 on 2019-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0003_faexpects_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='department',
            field=models.IntegerField(choices=[('', '選択'), (1, '西武'), (2, 'ソフトバンク'), (3, '楽天'), (4, 'ロッテ'), (5, '日本ハム'), (6, 'オリックス'), (7, '巨人'), (8, 'DeNA'), (9, '阪神'), (10, '広島'), (11, '中日'), (12, 'ヤクルト')], default=0, verbose_name='現所属球団'),
        ),
    ]
