# Generated by Django 2.2.6 on 2019-11-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0004_auto_20191121_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='faexpects',
            name='team',
            field=models.IntegerField(choices=[('', '選択'), (1, '西武'), (2, 'ソフトバンク'), (3, '楽天'), (4, 'ロッテ'), (5, '日本ハム'), (6, 'オリックス'), (7, '巨人'), (8, 'DeNA'), (9, '阪神'), (10, '広島'), (11, '中日'), (12, 'ヤクルト')], default=0, verbose_name='球団'),
        ),
    ]
