# Generated by Django 2.2.6 on 2019-11-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0006_auto_20191122_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faexpects',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'position': 1}, on_delete=django.db.models.deletion.CASCADE, to='fa_expects.Players', verbose_name='選手'),
        ),
    ]
