# Generated by Django 2.2.6 on 2019-11-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0007_auto_20191122_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='年齢')),
                ('position', models.IntegerField(choices=[(0, 'なし'), (1, '投手'), (2, '捕手'), (3, '一塁手'), (4, '二塁手'), (5, '三塁手'), (6, '遊撃手'), (7, '外野手'), (8, '内野手'), (9, '野手')], default=0, verbose_name='メインポジション')),
                ('dominant_hand', models.IntegerField(choices=[(0, 'なし'), (1, '右投右打'), (2, '右投左打'), (3, '右投両打'), (4, '左投左打')], default=0, verbose_name='利き手')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '要望',
                'verbose_name_plural': '要望',
            },
        ),
    ]
