# Generated by Django 2.2.6 on 2019-11-25 04:06

from django.db import migrations, models
import django.db.models.deletion
import fa_expects.models


class Migration(migrations.Migration):

    dependencies = [
        ('fa_expects', '0009_auto_20191122_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faexpects',
            name='player_id',
            field=models.ForeignKey(limit_choices_to=fa_expects.models.set_players_condition, on_delete=django.db.models.deletion.CASCADE, to='fa_expects.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='requestedconditions',
            name='position',
            field=models.IntegerField(choices=[(0, 'なし'), (1, '投手'), (2, '捕手'), (3, '一塁手'), (4, '二塁手'), (5, '三塁手'), (6, '遊撃手'), (7, '外野手')], default=0, verbose_name='メインポジション'),
        ),
    ]
